# Generated by Django 5.0.4 on 2024-05-09 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='customer_code',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='amount',
            new_name='item_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
