# Generated by Django 5.0.4 on 2024-05-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_author_customer_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_code',
            new_name='customerCode',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='customerName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_amount',
            new_name='itemAmount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_name',
            new_name='itemName',
        ),
    ]
