# Generated by Django 5.0.4 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_customer_code_customer_customercode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemAmount',
            field=models.IntegerField(),
        ),
    ]
