# Generated by Django 5.0.4 on 2024-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_itemamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='itemAmount',
            field=models.IntegerField(),
        ),
    ]
